# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "hozgans-terraform-bucket-for-remote-states"
    dynamodb_table = "hozgans-terraform-table-for-lock"
    encrypt        = true
    key            = "terragrunt/stacks/us-east-1/dev/blog/terraform.tfstate"
    region         = "us-east-1"
  }
}
